In [6]:
pwd

'/Lun2/rzz/kaldi-master/egs/zhiyong/GREAT_ASV_system/train/debug'

In [8]:
import os
import sys
sys.path.append('/Lun2/rzz/kaldi-master/egs/zhiyong/GREAT_ASV_system/train/debug' + '/../')

import time
import importlib

import torch
import training_utils
from torch.utils.data import *
from my_dataloader import *
from read_data import *
import config.config_debug as config
importlib.reload(config)
from model_bank import *

/home/dell/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [26]:
train_data = PickleDataSet_single('/Lun0/zhiyong/sdsvc_full_488_dataset/source_vox_7323_fulltrain.csv')
train_dataloader = My_DataLoader(train_data, batch_size=128, shuffle=False, \
sampler=SequentialSampler(train_data), \
batch_sampler=None, num_workers=8, collate_fn=None, \
pin_memory=False, drop_last=False, timeout=0, \
worker_init_fn=None, multiprocessing_context=None)

In [53]:
train_data = PickleDataSet('/Lun0/zhiyong/dataset/tmp_data_csv.csv')
train_dataloader = My_DataLoader(train_data, batch_size=None, shuffle=False, \
sampler=SequentialSampler(train_data), \
batch_sampler=None, num_workers=8, collate_fn=None, \
pin_memory=False, drop_last=False, timeout=0, \
worker_init_fn=None, multiprocessing_context=None)

In [67]:
train_data = PickleDataSet_single('/Lun0/zhiyong/sdsvc_full_488_dataset/target_sdsvc_488_fulltrain.csv')
train_dataloader = My_DataLoader(train_data, batch_size=128, shuffle=False, \
sampler=SequentialSampler(train_data), \
batch_sampler=None, num_workers=8, collate_fn=None, \
pin_memory=False, drop_last=False, timeout=0, \
worker_init_fn=None, multiprocessing_context=None)

In [40]:
p_count_dict = {}
for i in range(len(train_data.spkid2utt[0])):
    
    la = train_data.spkid2utt[0][i].split('/')[-1][0]
    if la not in p_count_dict.keys():
        p_count_dict[la] = 1
    else:
        p_count_dict[la] += 1

In [41]:
p_count_dict

{'0': 1098450,
 '1': 1098450,
 '2': 1098450,
 '3': 1098450,
 '4': 1098450,
 '5': 1098450,
 '6': 1098450,
 '7': 1098450,
 '8': 1098450,
 '9': 1098450}

In [68]:
count_dict_2 = {}
for count, [_, batch_label] in enumerate(train_dataloader):
    batch_label = batch_label.numpy()
    for i in batch_label:
        if i not in count_dict_2.keys():
            count_dict_2[i] = 1
        else:
            count_dict_2[i] += 1
    if (count+1) % 100 == 0:
        print(count)

99
199
299
399
499
599
699
799
899
999
1099
1199
1299
1399
1499
1599
1699
1799
1899
1999
2099
2199
2299
2399
2499
2599
2699
2799
2899
2999
3099
3199
3299
3399
3499
3599
3699
3799
3899
3999
4099
4199
4299
4399
4499
4599
4699
4799
4899
4999
5099
5199
5299
5399
5499
5599
5699


In [27]:
count_dict = {}
for count, [_, batch_label] in enumerate(train_dataloader):
    batch_label = batch_label.numpy()
    for i in batch_label:
        if i not in count_dict.keys():
            count_dict[i] = 1
        else:
            count_dict[i] += 1
    if (count+1) % 100 == 0:
        print(count)

99
199
299
399
499
599
699
799
899
999
1099
1199
1299
1399
1499
1599
1699
1799
1899
1999
2099
2199
2299
2399
2499
2599
2699
2799
2899
2999
3099
3199
3299
3399
3499
3599
3699
3799
3899
3999
4099
4199
4299
4399
4499
4599
4699
4799
4899
4999
5099
5199
5299
5399
5499
5599
5699
5799
5899
5999
6099
6199
6299
6399
6499
6599
6699
6799
6899
6999
7099
7199
7299
7399
7499
7599
7699
7799
7899
7999
8099
8199
8299
8399
8499
8599
8699
8799
8899
8999
9099
9199
9299
9399
9499
9599
9699
9799
9899
9999
10099
10199
10299
10399
10499
10599
10699
10799
10899
10999
11099
11199
11299
11399
11499
11599
11699
11799
11899
11999
12099
12199
12299
12399
12499
12599
12699
12799
12899
12999
13099
13199
13299
13399
13499
13599
13699
13799
13899
13999
14099
14199
14299
14399
14499
14599
14699
14799
14899
14999
15099
15199
15299
15399
15499
15599
15699
15799
15899
15999
16099
16199
16299
16399
16499
16599
16699
16799
16899
16999
17099
17199
17299
17399
17499
17599
17699
17799
17899
17999
18099
18199
18299
18399
18499
1

In [69]:
count_dict_2

{7323: 1500,
 7324: 1500,
 7325: 1500,
 7326: 1500,
 7327: 1500,
 7328: 1500,
 7329: 1500,
 7330: 1500,
 7331: 1500,
 7332: 1500,
 7333: 1500,
 7334: 1500,
 7335: 1500,
 7336: 1500,
 7337: 1500,
 7338: 1500,
 7339: 1500,
 7340: 1500,
 7341: 1500,
 7342: 1500,
 7343: 1500,
 7344: 1500,
 7345: 1500,
 7346: 1500,
 7347: 1500,
 7348: 1500,
 7349: 1500,
 7350: 1500,
 7351: 1500,
 7352: 1500,
 7353: 1500,
 7354: 1500,
 7355: 1500,
 7356: 1500,
 7357: 1500,
 7358: 1500,
 7359: 1500,
 7360: 1500,
 7361: 1500,
 7362: 1500,
 7363: 1500,
 7364: 1500,
 7365: 1500,
 7366: 1500,
 7367: 1500,
 7368: 1500,
 7369: 1500,
 7370: 1500,
 7371: 1500,
 7372: 1500,
 7373: 1500,
 7374: 1500,
 7375: 1500,
 7376: 1500,
 7377: 1500,
 7378: 1500,
 7379: 1500,
 7380: 1500,
 7381: 1500,
 7382: 1500,
 7383: 1500,
 7384: 1500,
 7385: 1500,
 7386: 1500,
 7387: 1500,
 7388: 1500,
 7389: 1500,
 7390: 1500,
 7391: 1500,
 7392: 1500,
 7393: 1500,
 7394: 1500,
 7395: 1500,
 7396: 1500,
 7397: 1500,
 7398: 1500,
 7399: 1500,

In [28]:
count_dict

{3425: 900,
 561: 1500,
 4766: 900,
 5290: 900,
 434: 1500,
 2347: 900,
 5728: 3900,
 184: 1500,
 2740: 2700,
 7039: 900,
 1113: 1500,
 4917: 900,
 1673: 1500,
 3962: 1500,
 3368: 2700,
 871: 1500,
 323: 1500,
 4600: 3900,
 3060: 2700,
 5143: 900,
 4139: 900,
 1566: 1500,
 1943: 1500,
 3771: 900,
 5688: 3900,
 3866: 1500,
 575: 1500,
 516: 1500,
 2524: 2700,
 4771: 900,
 5599: 900,
 3363: 900,
 6409: 900,
 822: 1500,
 2213: 900,
 4723: 900,
 848: 1500,
 1965: 1500,
 4020: 2700,
 6786: 900,
 6532: 2700,
 2352: 2700,
 7317: 900,
 23: 1500,
 885: 1500,
 3037: 900,
 1289: 1500,
 1522: 1500,
 3662: 1500,
 3574: 1500,
 511: 1500,
 2733: 900,
 5825: 900,
 2421: 900,
 3974: 1500,
 6115: 900,
 389: 1500,
 1348: 1500,
 1442: 1500,
 6805: 900,
 989: 1500,
 7260: 2700,
 388: 1500,
 7307: 900,
 119: 1500,
 6275: 900,
 6650: 900,
 3870: 1500,
 4349: 900,
 5214: 900,
 2198: 1500,
 359: 1500,
 5983: 900,
 683: 1500,
 478: 1500,
 5666: 900,
 2801: 900,
 5055: 900,
 4498: 900,
 5273: 900,
 1558: 1500,
 

In [56]:
to = 0
num_list = {}
for i in range(len(count_dict_2)):
    print(count_dict_2[i])
    to += count_dict_2[i]
    if count_dict_2[i] not in num_list:
        num_list[count_dict_2[i]] = 1
    else:
        num_list[count_dict_2[i]] += 1

1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1498
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500


1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1499
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1499
1499
1499
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1499
1499
1500
1500
1500
1500
1500
1499
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1499
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500


1500
1500
1499
1500
1500
1500
1499
1500
1500
1500
1500
1500
1499
1500
1499
1500
1500
1499
1500
1500
1499
1500
1500
1500
1500
1499
1499
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1499
1500
1499
1500
1499
1500
1500
1500
1500
1500
1500
1499
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1499
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1499
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500


In [57]:
num_list

{1497: 3, 1498: 36, 1499: 739, 1500: 6545}

In [60]:
to = 0
num_list = {}
for i in range(len(count_dict)):
    print(count_dict[i])
    to += count_dict[i]
    if count_dict[i] not in num_list:
        num_list[count_dict[i]] = 1
    else:
        num_list[count_dict[i]] += 1
#     if count_dict[i] != 1500:
#         print(i)
#         break

1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500
1500


1500
1500
1500
1500
1500
1500
1500
1500
1500
2100
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2700
900
1500
900
2

900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
900
900
900
3900
900
900
900
2700
9

In [61]:
num_list

{900: 3444, 1500: 2560, 2100: 1, 2700: 914, 3300: 1, 3900: 403}

In [65]:
import pickle
with open('prob_sparse_voxdata', 'wb') as handle:
    pickle.dump(count_dict, handle)

In [66]:
with open('normal_batched_voxdata', 'wb') as handle:
    pickle.dump(count_dict_2, handle)

In [91]:
loss = torch.nn.CrossEntropyLoss(weight=torch.tensor([1, 10]).float(), reduction='none')

In [80]:
a = torch.tensor([[1, 5], [2, 3], [3, 4]]).float()
labe = torch.tensor([0, 1, 1])

In [92]:
loss(a, labe)

tensor([4.0181, 3.1326, 3.1326])

In [86]:
loss(a, labe) * torch.tensor([1, 10, 10]).float()

tensor([4.0181, 3.1326, 3.1326])

In [93]:
for i in labe:
    if 
    print(i)

tensor(0)
tensor(1)
tensor(1)


In [95]:
labe*9 + 1

tensor([ 1, 10, 10])