In [1]:
import torch
from SpeakerNet import SpeakerNet

In [38]:
s = SpeakerNet('EPACA-TDNN', 'sgd', 'steplr', 'amsoftmax', nOut=512, nClasses=5994, lr=0.01, weight_decay=5e-4, 
              test_interval=10, max_epoch=100, lr_decay=0.01)

Initialised AMSoftmax m=0.300 s=15.000
Initialised SGD optimizer
Initialised step LR scheduler


In [34]:
s.__scheduler__.step()

In [40]:
a = s.__scheduler__.state_dict()

In [48]:
a['last_epoch'] = a['last_epoch'] - 1

In [49]:
a

{'step_size': 10,
 'gamma': 0.01,
 'base_lrs': [0.01],
 'last_epoch': 9,
 '_step_count': 1,
 '_get_lr_called_within_step': False,
 '_last_lr': [0.01]}

In [45]:
s.__scheduler__.load_state_dict(a)

In [47]:
s.__scheduler__.state_dict()

{'step_size': 10,
 'gamma': 0.01,
 'base_lrs': [0.01],
 'last_epoch': 10,
 '_step_count': 1,
 '_get_lr_called_within_step': False,
 '_last_lr': [0.01]}

In [8]:
s.__optimizer__.state_dict()

{'state': {},
 'param_groups': [{'lr': 0.01,
   'momentum': 0.9,
   'dampening': 0,
   'weight_decay': 0.0005,
   'nesterov': False,
   'initial_lr': 0.01,
   'params': [0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    75,
    76,
    77,
    78,
    79,
    80,
    81,
    82,
    83,
    84,
    85,
    86,
    87,
    88,
    89,
    90,
    91,
    92,
    93,
    94,
    95,
    96,
    97,
    98,
    99,
    100,
    101,
    102,
    103,
    104,

In [37]:
len(s.state_dict().keys())

202

In [50]:
import torch.nn.functional as F

In [52]:
ref_feat = torch.randn(10, 512)

In [53]:
com_feat = torch.randn(10, 512)

In [54]:
ref_feat.shape

torch.Size([10, 512])

In [68]:
ref_feat.shape

torch.Size([10, 512])

In [69]:
com_feat.transpose(0,1).shape

torch.Size([512, 10])

In [80]:
a = ref_feat[1]-com_feat[0]

In [81]:
torch.sqrt(torch.sum(a**2))

tensor(32.4549)

In [63]:
F.pairwise_distance(ref_feat, com_feat)

tensor([29.4692, 33.3921, 31.2939, 31.5184, 31.6852, 33.6739, 30.4412, 31.7020,
        30.7948, 30.8007])

In [71]:
ref_feat.unsqueeze(-1).shape

torch.Size([10, 512, 1])

In [73]:
com_feat.unsqueeze(-1).transpose(0,2).shape

torch.Size([1, 512, 10])

In [57]:
F.pairwise_distance(ref_feat.unsqueeze(-1), com_feat.unsqueeze(-1).transpose(0,2))

tensor([[29.4692, 30.3904, 30.5643, 31.3308, 31.2108, 33.7216, 30.0520, 30.6746,
         30.4927, 30.6383],
        [32.4549, 33.3921, 32.4060, 34.2440, 32.9469, 32.8640, 31.6555, 32.1605,
         31.4750, 32.6788],
        [31.0115, 30.8787, 31.2939, 32.4472, 31.4231, 32.5986, 30.1764, 31.4568,
         31.5361, 31.6564],
        [32.1484, 31.9802, 33.1354, 31.5184, 31.7081, 33.6083, 31.4724, 31.3120,
         31.8933, 32.1574],
        [32.7541, 29.9106, 30.7991, 32.6747, 31.6852, 32.7301, 30.3458, 32.0193,
         31.7741, 31.3324],
        [30.9358, 32.3993, 32.0035, 32.0844, 32.7673, 33.6739, 31.1249, 32.0505,
         32.5397, 33.6895],
        [31.1655, 31.4294, 32.0207, 33.9870, 31.4570, 32.0697, 30.4412, 32.4686,
         31.8435, 30.1598],
        [30.9397, 30.8462, 31.4230, 31.5767, 31.5441, 32.2569, 31.3480, 31.7020,
         30.6532, 31.6458],
        [32.6068, 31.5520, 31.7879, 34.1797, 32.2004, 31.2874, 31.1264, 31.8409,
         30.7948, 30.6863],
        [32.3118, 3

In [74]:
pdist = torch.nn.PairwiseDistance()

In [77]:
F.cosine_similarity(ref_feat.unsqueeze(-1), com_feat.unsqueeze(-1).transpose(0,2)).shape

torch.Size([10, 10])

In [75]:
pdist(ref_feat.unsqueeze(-1), com_feat.unsqueeze(-1).transpose(0,2))

tensor([[29.4692, 30.3904, 30.5643, 31.3308, 31.2108, 33.7216, 30.0520, 30.6746,
         30.4927, 30.6383],
        [32.4549, 33.3921, 32.4060, 34.2440, 32.9469, 32.8640, 31.6555, 32.1605,
         31.4750, 32.6788],
        [31.0115, 30.8787, 31.2939, 32.4472, 31.4231, 32.5986, 30.1764, 31.4568,
         31.5361, 31.6564],
        [32.1484, 31.9802, 33.1354, 31.5184, 31.7081, 33.6083, 31.4724, 31.3120,
         31.8933, 32.1574],
        [32.7541, 29.9106, 30.7991, 32.6747, 31.6852, 32.7301, 30.3458, 32.0193,
         31.7741, 31.3324],
        [30.9358, 32.3993, 32.0035, 32.0844, 32.7673, 33.6739, 31.1249, 32.0505,
         32.5397, 33.6895],
        [31.1655, 31.4294, 32.0207, 33.9870, 31.4570, 32.0697, 30.4412, 32.4686,
         31.8435, 30.1598],
        [30.9397, 30.8462, 31.4230, 31.5767, 31.5441, 32.2569, 31.3480, 31.7020,
         30.6532, 31.6458],
        [32.6068, 31.5520, 31.7879, 34.1797, 32.2004, 31.2874, 31.1264, 31.8409,
         30.7948, 30.6863],
        [32.3118, 3

In [82]:
listfilename = '/workspace/DATASET/server9_ssd/veri_test2.txt'

In [83]:
lines       = []
files       = []
feats       = {}
# tstart      = time.time()

## Read all lines
with open(listfilename) as listfile:
    while True:
        line = listfile.readline();
        if (not line):
            break;

        data = line.split();

        ## Append random label if missing
        if len(data) == 2: data = [random.randint(0,1)] + data

        files.append(data[1])
        files.append(data[2])
        lines.append(line)

setfiles = list(set(files))
setfiles.sort()

In [89]:
len(set(files))

4708

In [85]:
len(setfiles)

4708

In [99]:
a = [[0, 1, 2]]

In [95]:
list(a[2:])

[2]

In [97]:
import numpy as np

In [100]:
np.append(a, a, axis=0)

array([[0, 1, 2],
       [0, 1, 2]])